import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto, Barlow, Ysabeau_SC  } from "next/font/google";
import "./globals.css";
import Footer from "@/(components)/Footer"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const roboto = Roboto({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
  weight: ["100", "300", "500", "700"]
})
const barlow = Barlow({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-barlow',
  weight: ["100", "200", "300", "500", "700"]
})

const ysabeau = Ysabeau_SC({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-ysabeau',
  weight: ["100", "200", "300", "500", "700"]
})


export const metadata: Metadata = {
  title: "UniBound Consulting",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Footer/>
      </body>

    </html>
  );
}
